version: "1.0"
stages:
  - "clone"
  - "build"
  - "push"

steps:
  clone:
    stage: clone
    title: 'Cloning main repository...'
    type: git-clone
    repo: https://github.com/codefresh-io/${{CF_REPO_NAME}}
    revision: ${{CF_BRANCH}}
    credentials:
      username: github
      password: ${{secrets.secret-for-github.token}}

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "codefresh/committers-counter"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"

  parallel_push:
    stage: push
    type: parallel
    steps:
      push_to_codefresh_inc_gcr:
        stage: build
        title: 'Pushing image to codefresh-inc-gcr'
        type: push
        registry: codefresh-inc-gcr
        candidate: ${{build}}
        tags:
          - ${{CF_BRANCH_TAG_NORMALIZED}}
          - ${{CF_REVISION}}

      push_to_codefresh_enterprise_gcr:
        stage: build
        title: 'Pushing image to codefresh-enterprise'
        type: push
        registry: codefresh-enterprise
        candidate: ${{build}}
        tags:
          - ${{CF_BRANCH_TAG_NORMALIZED}}
          - ${{CF_REVISION}}

      push_to_quay:
        title: "Pushing image to quay"
        type: push
        registry: cf-quay
        candidate: ${{build}}
        tags:
          - ${{CF_BRANCH_TAG_NORMALIZED}}
          - ${{CF_REVISION}}

